version: 0.2

phases:
  install:
    commands:
      - npm install -g typescript ts-node
      - npm install

  build:
    commands:
      - export OLD_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - export OLD_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - temp_role=$(aws sts assume-role --role-session-name "next" --duration-seconds 10800 --role-arn "${ASSUME_ROLE_ARN}")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - ts-node ./packages/uat-data/scripts/insert-uat-data.ts
