version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - curl https://proxy.uat.ptl.bichard7.modernisation-platform.service.justice.gov.uk/users/login?redirect=/users
      - npm install
      - npm install -g ts-node

  build:
    commands:
      - REPEAT_SCENARIOS=10 DEPLOY_NAME=uat ts-node ./packages/uat-data/scripts/insert-uat-data.ts
