version: 0.2

phases:
  install:
    commands:
      - curl http://pnc.uat.ptl.bichard7.modernisation-platform.service.justice.gov.uk:3000/mocks
      - /bin/bash packages/e2e-test/scripts/configure_codebuild_image.sh
      - yum groupinstall -y "Development tools"
      - yum -y install jq gzip tar unzip openssl shadow-utils xz wget gnupg curl openvpn which chromium deltarpm
      - pip3 install --upgrade pip
      - pip3 install click botocore requests
      - npm install -g typescript ts-node

  build:
    commands:
      - set -e
      - TRIGGER=$(aws codepipeline list-pipeline-executions --pipeline-name cjse-bichard7-path-to-live-deploy-pipeline --query "pipelineExecutionSummaries[?pipelineExecutionId=='${CODEPIPELINE_EXECUTION_ID}'] .trigger.triggerDetail" --output text)
      - npm i
      - cd packages/e2e-test
      - export OLD_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - export OLD_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - temp_role=$(aws sts assume-role --role-session-name "next" --duration-seconds 10800 --role-arn "${ASSUME_ROLE_ARN}")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - aws ec2 describe-client-vpn-endpoints | jq -r ".ClientVpnEndpoints[0].DnsServers[0:2][]" | sed 's/^/nameserver /' | cat - /etc/resolv.conf > tmp && cp tmp /etc/resolv.conf
      - openvpn --config ~/cjse-${WORKSPACE}-config.ovpn --daemon --log /var/log/openvpn.log
      - bash ./scripts/setup-e2e-tests.sh
      - source ./workspaces/${WORKSPACE}.env
      - cd $CODEBUILD_SRC_DIR
      - S3_INCOMING_MESSAGE_BUCKET=bichard-7-uat-incoming-messages PNC_PORT=3000 REPEAT_SCENARIOS=10 DEPLOY_NAME=uat ts-node ./packages/uat-data/scripts/insert-uat-data.ts
