version: 0.2

phases:
  install:
    commands:
      - yum install -y openvpn
      - npm install
      - npm install -g ts-node

  pre_build:
    commands:
      - ./packages/uat-data/scripts/get-vpn-config.sh
      - openvpn --config ~/cjse-uat-config.ovpn --daemon
      - while ! grep -q "Initialization Sequence Completed" openvpn.log; do
          echo "VPN is still establishing...";
          sleep 2;
        done

  build:
    commands:
      - REPEAT_SCENARIOS=10 DEPLOY_NAME=uat ts-node ./packages/uat-data/scripts/insert-uat-data.ts
