version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - yum install -y openvpn
      - npm install
      - npm install -g ts-node

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR_bichard7_next_infrastructure
      - ./scripts/connect_vpn.sh

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - REPEAT_SCENARIOS=10 DEPLOY_NAME=uat ts-node ./packages/uat-data/scripts/insert-uat-data.ts
