version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - curl http://pnc.cjse.org:3000/mocks
      - npm install
      - npm install -g ts-node

  build:
    commands:
      - REPEAT_SCENARIOS=10 DEPLOY_NAME=uat ts-node ./packages/uat-data/scripts/insert-uat-data.ts
