--liquibase formatted sql
--changeset bjpirt:002-error-list

------------------------------------------------
-- DDL Statements for BR7OWN.ERROR_LIST
------------------------------------------------

 CREATE TABLE br7own.ERROR_LIST  (
		  ERROR_ID SERIAL PRIMARY KEY,
		  MESSAGE_ID VARCHAR(70) NOT NULL ,
		  PHASE INTEGER NOT NULL ,
		  ERROR_STATUS INTEGER ,
		  TRIGGER_STATUS INTEGER ,
		  ERROR_QUALITY_CHECKED INTEGER ,
		  TRIGGER_QUALITY_CHECKED INTEGER ,
		  TRIGGER_COUNT INTEGER NOT NULL ,
		  ERROR_LOCKED_BY_ID VARCHAR(32) ,
		  TRIGGER_LOCKED_BY_ID VARCHAR(32) ,
		  IS_URGENT SMALLINT NOT NULL ,
		  ASN VARCHAR(21) ,
		  COURT_CODE VARCHAR(7) ,
		  ANNOTATED_MSG TEXT NOT NULL ,
		  UPDATED_MSG TEXT ,
		  ERROR_REPORT VARCHAR(1000) NOT NULL ,
		  CREATE_TS TIMESTAMP NOT NULL ,
		  ERROR_REASON VARCHAR(350) ,
		  TRIGGER_REASON VARCHAR(350) ,
		  ERROR_COUNT INTEGER NOT NULL ,
		  USER_UPDATED_FLAG SMALLINT NOT NULL ,
		  COURT_DATE DATE ,
		  PTIURN VARCHAR(11) ,
		  COURT_NAME VARCHAR(500) ,
		  RESOLUTION_TS TIMESTAMP ,
		  MSG_RECEIVED_TS TIMESTAMP NOT NULL ,
		  ERROR_RESOLVED_BY VARCHAR(32) ,
		  TRIGGER_RESOLVED_BY VARCHAR(32) ,
		  ERROR_RESOLVED_TS TIMESTAMP ,
		  TRIGGER_RESOLVED_TS TIMESTAMP ,
		  DEFENDANT_NAME VARCHAR(500) ,
		  ORG_FOR_POLICE_FILTER CHAR(6) ,
		  COURT_ROOM VARCHAR(2) ,
		  COURT_REFERENCE VARCHAR(11) NOT NULL ,
		  ERROR_INSERT_TS TIMESTAMP ,
		  TRIGGER_INSERT_TS TIMESTAMP,
		  PNC_UPDATE_ENABLED CHAR(1),
		  DEFENDANT_NAME_UPPER VARCHAR(200)
		  	GENERATED ALWAYS AS (UPPER(DEFENDANT_NAME)) STORED ,
		  COURT_NAME_UPPER VARCHAR(200)
		  	GENERATED ALWAYS AS (UPPER(COURT_NAME)) STORED );

-- DDL Statements for unique constraints on Table BR7OWN.ERROR_LIST
CREATE UNIQUE INDEX UNIQUE_MESSAGE_ID
        ON br7own.ERROR_LIST (MESSAGE_ID);

-- DDL Statements to add index for "COURT_CODE" column to Table BR7OWN.ERROR_LIST
CREATE INDEX ERR_LST_COURTCD_IX
	ON br7own.ERROR_LIST (
		COURT_CODE );

-- DDL Statements to add index for "ERROR_LOCKED_BY_ID" column to Table BR7OWN.ERROR_LIST
CREATE INDEX ERR_LOCKED_ID_IX
	ON br7own.ERROR_LIST (
		ERROR_LOCKED_BY_ID );

-- DDL Statements to add index for "TRIGGER_LOCKED_BY_ID" column to Table BR7OWN.ERROR_LIST
CREATE INDEX TRG_LOCKED_ID_IX
	ON br7own.ERROR_LIST (
		TRIGGER_LOCKED_BY_ID );

-- DDL Statements to add index for "ORG_FOR_POLICE_FILTER" column to Table BR7OWN.ERROR_LIST
CREATE INDEX ERR_LST_ORGPOLF_IX
	ON br7own.ERROR_LIST (
		ORG_FOR_POLICE_FILTER );

-- DDL Statements to add index for "DEFENDANT_NAME_UPPER" column to Table BR7OWN.ERROR_LIST
CREATE INDEX ERR_LST_DEFNAME_IX
	ON br7own.ERROR_LIST (DEFENDANT_NAME_UPPER);

-- DDL Statements to add index for "COURT_NAME_UPPER" column to Table BR7OWN.ERROR_LIST
CREATE INDEX ERR_LST_CRTNAME_IX
        ON br7own.ERROR_LIST (COURT_NAME_UPPER);
