---
version: 0.2

env:
  variables:
    "NODE_OPTIONS": "--max_old_space_size=4096"

phases:
  build:
    commands:
      - ./scripts/install-goss.sh
      - ./scripts/build-core-worker-docker.sh
      # - ./scripts/build-api-docker.sh
      - ./scripts/build-message-forwarder-docker.sh
---

