---
version: 0.2

phases:
  install:
    commands:
      - yum install -y zip
  build:
    commands:
      - npm ci
      - npm run build:lambdas
      - ./scripts/codebuild_artifacts.sh
      - ./scripts/codebuild_dags.sh
---

