services:
  e2e-tests:
    image: e2etests
    environment:
      MQ_URL: failover:(stomp://activemq:61613)
      MQ_USER: ${DEFAULT_USER}
      MQ_PASSWORD: ${DEFAULT_PASSWORD}
      UI_HOST: nginx-auth-proxy
      UI_PORT: 4443
      UI_SCHEME: https
      USERS_SCHEME: https
      USERS_HOST: nginx-auth-proxy
      USERS_PORT: 4443
      PNC_HOST: pnc
      DB_HOST: postgres
      DB_USER: ${DEFAULT_USER}
      DB_PASSWORD: ${DEFAULT_PASSWORD}
      AWS_URL: http://localstack:4566
      S3_INCOMING_MESSAGE_BUCKET: incoming-messages
      MESSAGE_ENTRY_POINT: s3phase1
      RECORD: "false"
      TEST_TIMEOUT: 30000
      AUTH_TYPE: user-service
      AUDIT_LOG_API_URL: http://audit-log-api:5000
      TOTAL_CHUNKS: "${TOTAL_CHUNKS:-1}"
      CHUNK_NUMBER: "${CHUNK_NUMBER:-0}"
    depends_on:
      conductor:
        condition: service_healthy
      nginx-auth-proxy:
        condition: service_healthy
