# Overrides for CircleCI to boost I/O performance
# Mounts data in memory

services:
  postgres:
    tmpfs:
      - /var/lib/postgresql/data

  localstack:
    tmpfs:
      - /var/lib/localstack

  pnc:
    healthcheck:
      test: (echo >/dev/tcp/localhost/20001) && (echo >/dev/tcp/localhost/30001)
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 35s
    restart: "no"
