version: "3.2"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DEFAULT_USER}
      POSTGRES_PASSWORD: ${DEFAULT_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    command: postgres -c max_prepared_transactions=100 -c log_statement=all
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER}"
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 20s

  user-service:
    image: user-service
    environment:
      BASE_URL: https://localhost:4443/users
      DB_HOST: postgres
      INCORRECT_DELAY: 0
      TOKEN_EXPIRES_IN: 1 week
      TOKEN_ISSUER: Bichard
      TOKEN_SECRET: ${AUTH_JWT_SECRET}
    healthcheck:
      test: (echo >/dev/tcp/localhost/3000) && (echo >/dev/tcp/localhost/443)
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 20s
    depends_on:
      postgres:
        condition: service_healthy

  ui:
    image: ui
    environment:
      DB_HOST: postgres
      DB_USER: ${DEFAULT_USER}
      DB_PASSWORD: ${DEFAULT_PASSWORD}
      MQ_URL: tcp://activemq:61613
      MQ_USER: ${DEFAULT_USER}
      MQ_PASSWORD: ${DEFAULT_PASSWORD}
    ports:
      - 4080:443
    healthcheck:
      test: curl --insecure --fail -v https://localhost/elb-status
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 20s
    depends_on:
      postgres:
        condition: service_healthy

  # nginx-auth-proxy:
  #   image: nginx-auth-proxy
  #   ports:
  #     - 4443:4443
  #   environment:
  #     CJSE_NGINX_APP_DOMAIN: bichard7-liberty:9443
  #     CJSE_NGINX_AUDITLOGGING_DOMAIN: nginx-auth-proxy:4443/elb-status
  #     CJSE_NGINX_BICHARDBACKEND_DOMAIN: bichard7-liberty:9443
  #     CJSE_NGINX_PORT_HTTPS: 4443
  #     CJSE_NGINX_PROXYSSLVERIFY: "off"
  #     CJSE_NGINX_STATICSERVICE_DOMAIN: nginx-auth-proxy:4443/elb-status
  #     CJSE_NGINX_UI_DOMAIN: ui
  #     CJSE_NGINX_USERSERVICE_DOMAIN: user-service
  #   healthcheck:
  #     test: curl --insecure --fail -v https://localhost:4443/elb-status
  #     interval: 2s
  #     timeout: 2s
  #     retries: 10
  #     start_period: 20s
  #   depends_on:
  #     user-service:
  #       condition: service_healthy
  #     ui:
  #       condition: service_healthy

  audit-log-api:
    image: natenho/mockaco
    ports:
      - 3011:5000
    volumes:
      - ./audit-log-api:/app/Mocks
    healthcheck:
      test: wget -q http://localhost:5000/health -O -
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 10s
