version: "3.2"
services:
  bichard7-liberty:
    environment:
      ENABLE_PHASE_1: "true"
      PHASE_1_RESUBMIT_QUEUE_NAME: "JMS/Phase1ResubmitQueue"
  message-forwarder:
    environment:
      DESTINATION_TYPE: mq
