---
version: 0.2

env:
  variables:
    REPOSITORY_NAME: "conductor"
    SOURCE_REPOSITORY_NAME: "amazon-linux2023-base"
    CONTEXT_DIR: environment/conductor
  exported-variables:
    - CONDUCTOR_IMAGE_HASH

phases:
  build:
    commands:
      - ./scripts/install-goss.sh
      - . ./scripts/build_and_push_image.sh
