@startuml
set separator none
title Bichard - Conductor - Components

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

ContainerDb(Bichard.BichardDatabase, "Bichard Database", $techn="PostgreSQL", $descr="", $tags="", $link="")
Container(Bichard.AuditLog, "Audit Log", $techn="", $descr="", $tags="", $link="")
Container(Bichard.PNCAPI, "PNC API", $techn="", $descr="", $tags="", $link="")

Container_Boundary("Bichard.Conductor_boundary", "Conductor", $tags="") {
  Component(Bichard.Conductor.BichardNextCore, "Bichard Next Core", $techn="Next.js, TypeScript", $descr="The code to replace the processing logic of Bichard7", $tags="", $link="")
}

Rel(Bichard.AuditLog, Bichard.BichardDatabase, "", $techn="", $tags="", $link="")
Rel(Bichard.Conductor.BichardNextCore, Bichard.AuditLog, "", $techn="", $tags="", $link="")
Rel(Bichard.Conductor.BichardNextCore, Bichard.BichardDatabase, "Reads from and writes to", $techn="", $tags="", $link="")
Rel(Bichard.Conductor.BichardNextCore, Bichard.PNCAPI, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml