@startuml
set separator none
title Bichard - Message Transfer Lambda - Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

System(ExISS, "ExISS", $descr="Exchange Integrated Shared Services", $tags="", $link="")
Container(Bichard.Conductor, "Conductor", $techn="", $descr="", $tags="", $link="")

Container_Boundary("Bichard.MessageTransferLambda_boundary", "Message Transfer Lambda", $tags="") {
  ComponentQueue(Bichard.MessageTransferLambda.ExternalIncomingS3bucket, "External Incoming S3 bucket", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.MessageTransferLambda.Transferlambda, "Transfer lambda", $techn="", $descr="", $tags="", $link="")
  ComponentQueue(Bichard.MessageTransferLambda.InternalIncomingS3bucket, "Internal Incoming S3 bucket", $techn="", $descr="", $tags="", $link="")
  ComponentQueue(Bichard.MessageTransferLambda.SQSqueue, "SQS queue", $techn="", $descr="", $tags="", $link="")
}

Rel(Bichard.MessageTransferLambda.SQSqueue, Bichard.Conductor, "", $techn="", $tags="", $link="")
Rel(ExISS, Bichard.MessageTransferLambda.ExternalIncomingS3bucket, "", $techn="", $tags="", $link="")
Rel(Bichard.MessageTransferLambda.ExternalIncomingS3bucket, Bichard.MessageTransferLambda.Transferlambda, "", $techn="", $tags="", $link="")
Rel(Bichard.MessageTransferLambda.Transferlambda, Bichard.MessageTransferLambda.InternalIncomingS3bucket, "", $techn="", $tags="", $link="")
Rel(Bichard.MessageTransferLambda.InternalIncomingS3bucket, Bichard.MessageTransferLambda.SQSqueue, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml