@startuml
set separator none
title Bichard - LEDS Proxy - Components

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

System(LEDS, "LEDS", $descr="Law Enforcement Data System", $tags="", $link="")
System(NIAM, "NIAM", $descr="National Identity Access Management service", $tags="", $link="")
Container(Bichard.BichardAPI, "Bichard API", $techn="TypeScript, Fastify & Zod", $descr="An API to remove DB actions from UI and to be Audit Logs", $tags="", $link="")

Container_Boundary("Bichard.LEDSProxy_boundary", "LEDS Proxy", $tags="") {
  Component(Bichard.LEDSProxy.ProxyLambda, "Proxy Lambda", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.LEDSProxy.LEDSTransitGateway, "LEDS Transit Gateway", $techn="", $descr="Access to LEDS environment is via a Transit Gateway managed by the LEDS team", $tags="", $link="")
}

Rel(Bichard.BichardAPI, Bichard.LEDSProxy.ProxyLambda, "Encrypted via HTTPS", $techn="", $tags="", $link="")
Rel(Bichard.BichardAPI, NIAM, "via Internet", $techn="Gets auth token to access LEDS API", $tags="", $link="")
Rel(Bichard.LEDSProxy.ProxyLambda, Bichard.LEDSProxy.LEDSTransitGateway, "", $techn="Encrypted via mTLS", $tags="", $link="")
Rel(Bichard.LEDSProxy.LEDSTransitGateway, LEDS, "", $techn="Encrypted via mTLS", $tags="", $link="")

SHOW_LEGEND(true)
@enduml