@startuml
set separator none
title System Landscape

left to right direction

!include <C4/C4>
!include <C4/C4_Context>

AddBoundaryTag("CJSE", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
Boundary(group_1, "CJSE", $tags="CJSE") {
  System(Bichard, "Bichard", $descr="", $tags="", $link="")
  System(PSNProxy, "PSN Proxy", $descr="Q-Solution", $tags="", $link="")
  System(ExISS, "ExISS", $descr="", $tags="", $link="")
}

AddBoundaryTag("HMCTS", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
Boundary(group_2, "HMCTS", $tags="HMCTS") {
  System(CommonPlatform, "Common Platform", $descr="", $tags="", $link="")
  System(Libra, "Libra", $descr="", $tags="", $link="")
}

AddBoundaryTag("Home Office - Police", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
Boundary(group_3, "Home Office - Police", $tags="Home Office - Police") {
  System(PoliceNationalComputer, "Police National Computer", $descr="", $tags="", $link="")
}

Person(PoliceUser, "Police User", $descr="", $tags="", $link="")
System(CJSM, "CJSM", $descr="", $tags="", $link="")

Rel(PoliceUser, PSNProxy, "Uses", $techn="", $tags="", $link="")
Rel(PoliceUser, PoliceNationalComputer, "Uses", $techn="", $tags="", $link="")
Rel(CJSM, PoliceUser, "Gets email", $techn="", $tags="", $link="")
Rel(CommonPlatform, ExISS, "Sends result of a court case", $techn="", $tags="", $link="")
Rel(Libra, ExISS, "Sends result of a court case", $techn="", $tags="", $link="")
Rel(PSNProxy, PoliceNationalComputer, "Uses", $techn="", $tags="", $link="")
Rel(Bichard, PSNProxy, "", $techn="", $tags="", $link="")
Rel(PSNProxy, PoliceNationalComputer, "", $techn="", $tags="", $link="")
Rel(PSNProxy, Bichard, "", $techn="", $tags="", $link="")
Rel(Bichard, CJSM, "Sends verification code", $techn="", $tags="", $link="")
Rel(ExISS, Bichard, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml