---
version: 0.2

env:
  variables:
    "NODE_OPTIONS": "--max_old_space_size=4096"

phases:
  install:
    commands:
      - yum install -y zip
  build:
    commands:
      - npm ci
      - ./scripts/build-docker.sh
---

