export enum PNCMessageType {
  ASN_ENQUIRY = "ENQASI",
  APPEALS_UPDATE = "APPHRD",
  COMMITTED_SENTENCING = "COMSEN",
  NORMAL_DISPOSAL = "DISARR",
  REMAND = "NEWREM",
  SENTENCE_DEFERRED = "SENDEF",
  DISPOSAL_UPDATED = "SUBVAR",
  PENALTY_HEARING = "PENHRG"
}
