@startuml
set separator none
title Bichard - Audit Log - Components

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

skinparam svgDimensionStyle false
skinparam preserveAspectRatio meet
Container(Bichard.ActiveMQ, "Active MQ", $techn="Active MQ", $descr="", $tags="", $link="")
ContainerDb(Bichard.BichardDatabase, "Bichard Database", $techn="PostgreSQL", $descr="", $tags="", $link="")

Container_Boundary("Bichard.AuditLog_boundary", "Audit Log", $tags="") {
  Component(Bichard.AuditLog.AuditLogAPIGateway, "Audit Log API Gateway", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.AuditLog.AuditLogAPILambda, "Audit Log API Lambda", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.AuditLog.DynamoDB, "DynamoDB", $techn="DynamoDB", $descr="", $tags="", $link="")
}

Rel_D(Bichard.AuditLog.AuditLogAPILambda, Bichard.AuditLog.DynamoDB, "", $techn="", $tags="", $link="")
Rel_D(Bichard.AuditLog.AuditLogAPILambda, Bichard.BichardDatabase, "", $techn="", $tags="", $link="")
Rel_D(Bichard.AuditLog.AuditLogAPILambda, Bichard.ActiveMQ, "", $techn="", $tags="", $link="")
Rel_D(Bichard.AuditLog.AuditLogAPIGateway, Bichard.AuditLog.AuditLogAPILambda, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml