@startuml
set separator none
title Bichard - Monitoring - Components

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

skinparam svgDimensionStyle false
skinparam preserveAspectRatio meet
Container(Bichard.BichardJavaApplication, "Bichard Java Application", $techn="Java EE", $descr="", $tags="", $link="")
System(Slack, "Slack", $descr="An instant messaging service used by Made Tech", $tags="", $link="../../slack/context/")
System(PagerDuty, "PagerDuty", $descr="An alert tool for instances when the systems trigger an alarm", $tags="", $link="../../pagerduty/context/")

Container_Boundary("Bichard.Monitoring_boundary", "Monitoring", $tags="") {
  Component(Bichard.Monitoring.OpenSearch, "OpenSearch", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.Monitoring.Prometheus, "Prometheus", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.Monitoring.PrometheusCloudWatchExporter, "Prometheus CloudWatch Exporter", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.Monitoring.PrometheusBlackBoxExporter, "Prometheus Black Box Exporter", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.Monitoring.Grafana, "Grafana", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.Monitoring.LogStash, "LogStash", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.Monitoring.CloudWatchLogs, "CloudWatch Logs", $techn="", $descr="Logs gathered from all AWS services", $tags="", $link="")
  Component(Bichard.Monitoring.CloudWatchMetrics, "CloudWatch Metrics", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.Monitoring.Slackmessagehandler, "Slack message handler", $techn="", $descr="", $tags="", $link="")
  ComponentQueue(Bichard.Monitoring.SNS, "SNS", $techn="", $descr="", $tags="", $link="")
}

Rel_D(Bichard.Monitoring.PrometheusBlackBoxExporter, Bichard.Monitoring.Prometheus, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Monitoring.PrometheusBlackBoxExporter, Bichard.BichardJavaApplication, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Monitoring.PrometheusBlackBoxExporter, Bichard.Monitoring.Grafana, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Monitoring.PrometheusBlackBoxExporter, Bichard.Monitoring.OpenSearch, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Monitoring.PrometheusCloudWatchExporter, Bichard.Monitoring.Prometheus, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Monitoring.PrometheusCloudWatchExporter, Bichard.Monitoring.CloudWatchMetrics, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Monitoring.Prometheus, Bichard.Monitoring.SNS, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Monitoring.CloudWatchMetrics, Bichard.Monitoring.SNS, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Monitoring.Prometheus, Bichard.Monitoring.Grafana, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Monitoring.LogStash, Bichard.Monitoring.OpenSearch, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Monitoring.CloudWatchLogs, Bichard.Monitoring.LogStash, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Monitoring.SNS, PagerDuty, "Sends message", $techn="", $tags="", $link="")
Rel_D(Bichard.Monitoring.SNS, Bichard.Monitoring.Slackmessagehandler, "Sends message", $techn="", $tags="", $link="")
Rel_D(Bichard.Monitoring.Slackmessagehandler, Slack, "Sends message", $techn="via TLS Webhook", $tags="", $link="")

SHOW_LEGEND(true)
@enduml