@startuml
set separator none
title Bichard - Reporting - Components

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

skinparam svgDimensionStyle false
skinparam preserveAspectRatio meet
Container(Bichard.StaticFileService, "Static File Service", $techn="", $descr="", $tags="", $link="")
ContainerDb(Bichard.BichardDatabase, "Bichard Database", $techn="PostgreSQL", $descr="", $tags="", $link="")
Container(Bichard.EmailSystem, "Email System", $techn="Postfix", $descr="", $tags="", $link="")
Container(Bichard.AuditLog, "Audit Log", $techn="", $descr="", $tags="", $link="")

Container_Boundary("Bichard.Reporting_boundary", "Reporting", $tags="") {
  Component(Bichard.Reporting.AutomationReport, "Automation Report", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.Reporting.CommonPlatformReport, "Common Platform Report", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.Reporting.MPSReport, "MPS Report", $techn="", $descr="", $tags="", $link="")
  Component(Bichard.Reporting.TopExceptionsReport, "Top Exceptions Report", $techn="", $descr="", $tags="", $link="")
}

Rel_D(Bichard.AuditLog, Bichard.BichardDatabase, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Reporting.AutomationReport, Bichard.AuditLog, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Reporting.CommonPlatformReport, Bichard.AuditLog, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Reporting.AutomationReport, Bichard.StaticFileService, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Reporting.TopExceptionsReport, Bichard.StaticFileService, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Reporting.CommonPlatformReport, Bichard.EmailSystem, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Reporting.MPSReport, Bichard.BichardDatabase, "", $techn="", $tags="", $link="")
Rel_D(Bichard.Reporting.TopExceptionsReport, Bichard.AuditLog, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml