@startuml
set separator none
title Old Bichard

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

skinparam svgDimensionStyle false
skinparam preserveAspectRatio meet
System(CJSM, "CJSM", "", $tags="")[[../../cjsm/context/]]
System(PSNProxy, "PSN Proxy", "Q-Solution", $tags="")[[../../psn-proxy/context/]]
System(ExISS, "ExISS", "", $tags="")[[../../exiss/context/]]

System_Boundary("Bichard_boundary", "Bichard", $tags="") {
  Container(Bichard.Beanconnect, "Beanconnect", "", $tags="")
  Container(Bichard.MessageTransferLambda, "Message Transfer Lambda", "", $tags="")[[../component/]]
  Container(Bichard.IncomingMessageHandlerStepFunction, "Incoming Message Handler Step Function", "", $tags="")[[../component/]]
  Container(Bichard.EventLambda, "Event Lambda", "", $tags="")
  Container(Bichard.EventHandlerStepFunction, "Event Handler Step Function", "", $tags="")[[../component/]]
  Container(Bichard.ActiveMQ, "Active MQ", "Active MQ", "", $tags="")
  Container(Bichard.NginxAuthProxy, "Nginx Auth Proxy", "Nginx", "", $tags="")
  ContainerDb(Bichard.BichardDatabase, "Bichard Database", "PostgreSQL", "", $tags="")
  Container(Bichard.EmailSystem, "Email System", "Postfix", "", $tags="")
  Container(Bichard.BichardJavaApplication, "Bichard Java Application", "Java EE", "", $tags="")
  Container(Bichard.BichardUserService, "Bichard User Service", "Next.js, TypeScript & React", "An application to provide user authentication and user management", $tags="")
  Container(Bichard.AuditLog, "Audit Log", "", $tags="")[[../component/]]
  Container(Bichard.StaticFileService, "Static File Service", "", $tags="")
  Container(Bichard.Reporting, "Reporting", "", $tags="")[[../component/]]
  Container(Bichard.Monitoring, "Monitoring", "", $tags="")[[../component/]]
}

Rel_D(Bichard.AuditLog, Bichard.BichardDatabase, "", $tags="")
Rel_D(Bichard.AuditLog, Bichard.ActiveMQ, "", $tags="")
Rel_D(Bichard.Reporting, Bichard.AuditLog, "", $tags="")
Rel_D(Bichard.Reporting, Bichard.StaticFileService, "", $tags="")
Rel_D(Bichard.Reporting, Bichard.EmailSystem, "", $tags="")
Rel_D(Bichard.Reporting, Bichard.BichardDatabase, "", $tags="")
Rel_D(Bichard.Monitoring, Bichard.BichardJavaApplication, "", $tags="")
Rel_D(Bichard.BichardJavaApplication, Bichard.Beanconnect, "", $tags="")
Rel_D(Bichard.Beanconnect, PSNProxy, "", $tags="")
Rel_D(PSNProxy, Bichard.NginxAuthProxy, "", $tags="")
Rel_D(Bichard.EmailSystem, CJSM, "Sends verification code", $tags="")
Rel_D(Bichard.BichardUserService, Bichard.EmailSystem, "Sends verification code", $tags="")
Rel_D(Bichard.NginxAuthProxy, Bichard.BichardJavaApplication, "", $tags="")
Rel_D(Bichard.NginxAuthProxy, Bichard.BichardUserService, "Uses", $tags="")
Rel_D(Bichard.NginxAuthProxy, Bichard.StaticFileService, "", $tags="")
Rel_D(Bichard.BichardUserService, Bichard.BichardDatabase, "Reads from / Writes to", $tags="")
Rel_D(Bichard.BichardJavaApplication, Bichard.BichardDatabase, "Reads from / Writes to", $tags="")
Rel_D(ExISS, Bichard.MessageTransferLambda, "", $tags="")
Rel_D(Bichard.MessageTransferLambda, Bichard.IncomingMessageHandlerStepFunction, "", $tags="")
Rel_D(Bichard.IncomingMessageHandlerStepFunction, Bichard.AuditLog, "", $tags="")
Rel_D(Bichard.IncomingMessageHandlerStepFunction, Bichard.ActiveMQ, "", $tags="")
Rel_D(Bichard.ActiveMQ, Bichard.EventLambda, "", $tags="")
Rel_D(Bichard.EventLambda, Bichard.EventHandlerStepFunction, "", $tags="")
Rel_D(Bichard.EventHandlerStepFunction, Bichard.AuditLog, "", $tags="")
Rel_D(Bichard.ActiveMQ, Bichard.BichardJavaApplication, "", $tags="")
Rel_D(Bichard.BichardJavaApplication, Bichard.ActiveMQ, "", $tags="")

SHOW_LEGEND(true)
@enduml