@startuml
set separator none
title System Landscape

left to right direction

!include <C4/C4>
!include <C4/C4_Context>

skinparam svgDimensionStyle false
skinparam preserveAspectRatio meet
AddBoundaryTag("CJSE", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_1, "CJSE", $tags="CJSE") {
  System(Bichard, "Bichard", $descr="", $tags="", $link="")
  System(PSNProxy, "PSN Proxy", $descr="Q-Solution", $tags="", $link="")
  System(ExISS, "ExISS", $descr="", $tags="", $link="")
}

AddBoundaryTag("HMCTS", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_2, "HMCTS", $tags="HMCTS") {
  System(CommonPlatform, "Common Platform", $descr="", $tags="", $link="common-platform/context/")
  System(Libra, "Libra", $descr="", $tags="", $link="libra/context/")
}

AddBoundaryTag("Home Office - Police", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_3, "Home Office - Police", $tags="Home Office - Police") {
  System(PoliceNationalComputer, "Police National Computer", $descr="", $tags="", $link="police-national-computer/context/")
}

Person(PoliceUser, "Police User", $descr="", $tags="", $link="")
System(CJSM, "CJSM", $descr="", $tags="", $link="cjsm/context/")

Rel_D(PoliceUser, PSNProxy, "Uses", $techn="", $tags="", $link="")
Rel_D(PoliceUser, PoliceNationalComputer, "Uses", $techn="", $tags="", $link="")
Rel_D(CJSM, PoliceUser, "Gets email", $techn="", $tags="", $link="")
Rel_D(CommonPlatform, ExISS, "Sends result of a court case", $techn="", $tags="", $link="")
Rel_D(Libra, ExISS, "Sends result of a court case", $techn="", $tags="", $link="")
Rel_D(PSNProxy, PoliceNationalComputer, "Uses", $techn="", $tags="", $link="")
Rel_D(Bichard, PSNProxy, "", $techn="", $tags="", $link="")
Rel_D(PSNProxy, PoliceNationalComputer, "", $techn="", $tags="", $link="")
Rel_D(PSNProxy, Bichard, "", $techn="", $tags="", $link="")
Rel_D(Bichard, CJSM, "Sends verification code", $techn="", $tags="", $link="")
Rel_D(ExISS, Bichard, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml