"use strict";
exports.__esModule = true;
var express_1 = require("express");
var auth_1 = require("../middleware/auth");
var validate_1 = require("../middleware/validate");
var courtCases_1 = require("../controllers/courtCases");
var router = (0, express_1.Router)();
router.use(auth_1["default"]);
router.get("/", validate_1.validateCaseListQueryParams, courtCases_1.getCourtCases);
exports["default"] = router;
