import { mockEnquiryFromNCM, mockUpdate } from "../../utils/pncMocks"

import type Bichard from "../../utils/world"

export default (ncm: string, world: Bichard) => [
  mockEnquiryFromNCM(ncm, world),
  mockUpdate("CXU02", {
    expectedRequest:
      "<FSC>K01YZ</FSC><IDS>K00/415366U PICADILLUS              </IDS><CCR>K97/1626/8395Q                 </CCR><COU>I2576                                                                       PICADILLUS/THETUBE                                    260920110000</COU><CCH>K001              TH68006 </CCH><ADJ>INOT GUILTY   NOT GUILTY    260920110000 </ADJ><DIS>I2050                      00                                                                            </DIS><ASR>K11/01ZD/01/415366U                    </ASR><ACH>I                                                                                                                                            TH68072                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     NKINGSTON HIGH STREET                                                                                                                                                                                                                   01ZD28112010                </ACH><ADJ>IGUILTY       GUILTY        260920110000 </ADJ><DIS>I1018M12                   00                                                                            </DIS>"
  })
]
