export const XML_DECLARATION = '<?xml version="1.0" standalone="yes"?>'

//FSC
export const UPDATE_TYPE_FIELD_LENGTH = 1
export const FORCE_STATION_CODE_FIELD_LENGTH = 4

//IDS
export const PNC_IDENTIFIER_FIELD_LENGTH = 11
export const PNC_CHECK_NAME_FIELD_LENGTH = 12
export const CRO_NUMBER_FIELD_LENGTH = 12

//CCR
export const COURT_CASE_REFERENCE_FIELD_LENGTH = 15
export const CRIME_OFFENCE_REFERENCE_FIELD_LENGTH = 15

//COF
export const REFERENCE_NUMBER_FIELD_LENGTH = 3
export const OFFENCE_QUALIFIER1_FIELD_LENGTH = 2
export const OFFENCE_QUALIFIER2_FIELD_LENGTH = 2
export const ACPO_OFFENCE_CODE_FIELD_LENGTH = 13
export const CJS_OFFENCE_CODE_FIELD_LENGTH = 8
export const OFFENCE_START_DATE_FIELD_LENGTH = 8
export const OFFENCE_START_TIME_FIELD_LENGTH = 4
export const OFFENCE_END_DATE_FIELD_LENGTH = 8
export const OFFENCE_END_TIME_FIELD_LENGTH = 4

//ADJ
export const PLEA_FIELD_SIZE = 13
export const ADJUDICATION_FIELD_SIZE = 14
export const DATE_OF_SENTENCE_FIELD_SIZE = 8
export const OFFENCE_TIC_NUMBER_FIELD_SIZE = 4
export const WEED_FLAG_FIELD_LENGTH = 1

//DIS
export const DISPOSAL_TYPE_FIELD_LENGTH = 4
export const DISPOSAL_QTY_DURATION_FIELD_LENGTH = 4
export const DISPOSAL_QTY_DATE_FIELD_LENGTH = 8
export const DISPOSAL_QTY_MONETARY_VALUE_FIELD_LENGTH = 10
export const DISPOSAL_QTY_UNITS_FINED_FIELD_LENGTH = 2
export const DISPOSAL_QUALIFIERS_FIELD_LENGTH = 12
export const DISPOSAL_TEXT_FIELD_LENGTH = 64

//GMH
export const GMH_FIELD_LENGTH = 116
export const GMT_FIELD_LENGTH = 20
