export const XML_DECLARATION = '<?xml version="1.0" standalone="yes"?>'
export const UPDATE_TYPE = "K"
export const OFFENCE_UPDATE_TYPE = "I"
export const DEFAULT_QTY_UNITS = "00"

//FSC
export const UPDATE_TYPE_FIELD_LENGTH = 1
export const FORCE_STATION_CODE_FIELD_LENGTH = 4

//IDS
export const PNC_IDENTIFIER_FIELD_LENGTH = 11
export const PNC_CHECK_NAME_FIELD_LENGTH = 12
export const CRO_NUMBER_FIELD_LENGTH = 12

//ASR
export const ARREST_SUMMONS_NUMBER_FIELD_LENGTH = 23

//CCR
export const COURT_CASE_REFERENCE_FIELD_LENGTH = 15
export const CRIME_OFFENCE_REFERENCE_FIELD_LENGTH = 15

//COF
export const REFERENCE_NUMBER_FIELD_LENGTH = 3
export const OFFENCE_QUALIFIER1_FIELD_LENGTH = 2
export const OFFENCE_QUALIFIER2_FIELD_LENGTH = 2
export const ACPO_OFFENCE_CODE_FIELD_LENGTH = 13
export const CJS_OFFENCE_CODE_FIELD_LENGTH = 8
export const OFFENCE_START_DATE_FIELD_LENGTH = 8
export const OFFENCE_START_TIME_FIELD_LENGTH = 4
export const OFFENCE_END_DATE_FIELD_LENGTH = 8
export const OFFENCE_END_TIME_FIELD_LENGTH = 4

//COU
export const COURT_CODE_FIELD_LENGTH = 4
export const NAME_CONVICTED_FIELD_LENGTH = 54
export const DATE_OF_HEARING_FIELD_LENGTH = 8
export const NUMBER_OF_TICS_FIELD_LENGTH = 4

//ADJ
export const PLEA_FIELD_LENGTH = 13
export const ADJUDICATION_FIELD_LENGTH = 14
export const DATE_OF_SENTENCE_FIELD_LENGTH = 8
export const OFFENCE_TIC_NUMBER_FIELD_LENGTH = 4
export const WEED_FLAG_FIELD_LENGTH = 1

//DIS
export const DISPOSAL_TYPE_FIELD_LENGTH = 4
export const DISPOSAL_QTY_DURATION_FIELD_LENGTH = 4
export const DISPOSAL_QTY_DATE_FIELD_LENGTH = 8
export const DISPOSAL_QTY_MONETARY_VALUE_FIELD_LENGTH = 10
export const DISPOSAL_QTY_UNITS_FINED_FIELD_LENGTH = 2
export const DISPOSAL_QUALIFIERS_FIELD_LENGTH = 12
export const DISPOSAL_TEXT_FIELD_LENGTH = 64

//GMH
export const GMH_FIELD_LENGTH = 116
export const GMT_FIELD_LENGTH = 20

//REM
export const REMAND_DATE_FIELD_LENGTH = 8
export const REMAND_RESULT_FIELD_LENGTH = 1
export const REMAND_LOCATION_FFSS_FIELD_LENGTH = 4
export const REMAND_LOCATION_COURT_FIELD_LENGTH = 4
export const COURT_NAME_FIELD_LENGTH = 71
export const NEXT_APPEARANCE_DATE_FIELD_LENGTH = 8
export const NEXT_APPEARANCE_LOCATION_FIELD_LENGTH = 4
export const BAIL_CONDITIONS_FIELD_LENGTH = 4000
export const BAIL_ADDRESS_FIELD_LENGTH = 167
export const BREACH_OF_BAIL_CONDITIONS_FIELD_LENGTH = 166
export const CUSTODY_FORCE_STATION_CODE_FIELD_LENGTH = 4
export const INSTITUTION_CODE_FIELD_LENGTH = 4
export const PRISONER_NUMBER_FIELD_LENGTH = 6
export const CUSTODY_TEXT_FIELD_LENGTH = 256
export const NEXT_APPEARANCE_LOCATION_FFSS_FIELD_LENGTH = 4
export const LOCAL_AUTHORITY_CODE_FIELD_LENGTH = 4
export const LOCAL_AUTHORITY_NAME_FIELD_LENGTH = 70
export const LOCAL_AUTHORITY_SECURE_UNIT_MARKER_FIELD_LENGTH = 1
export const SOCIAL_WORKER_NAME_FIELD_LENGTH = 54
export const SOCIAL_WORKER_TELEPHONE_FIELD_LENGTH = 49

//CCH
export const COURT_REFERENCE_NUMBER_FIELD_LENGTH = 3
export const OFFENCE_QUALIFIER_FIELD_LENGTH = 4
export const CCH_ACPO_OFFENCE_CODE_FIELD_LENGTH = 10
