version: "3.2"
services:
  mq:
    image: rmohr/activemq
    ports:
      - 59161:8161
      - 62613:61613
    volumes:
      - ./activemq.xml:/opt/activemq/conf/activemq.xml

  pg:
    build:
      context: .
      dockerfile: PgDockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bichard
      POSTGRES_USER: bichard
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5434:5432
    command: postgres -c max_prepared_transactions=100 -c log_statement=all
    volumes:
      - ./pg-schema.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "psql", "-U", "bichard", "-c", "SELECT 1;"]
      interval: 2s
      timeout: 5s
      retries: 50

  conductor:
    image: conductor
    environment:
      CJSE_CONDUCTOR_POSTGRES_URL: ${CJSE_CONDUCTOR_POSTGRES_URL:-jdbc:postgresql://pg:5432/conductor}
      CJSE_CONDUCTOR_POSTGRES_USER: ${CJSE_CONDUCTOR_POSTGRES_USER:-conductor}
      CJSE_CONDUCTOR_POSTGRES_PASSWORD: ${CJSE_CONDUCTOR_POSTGRES_PASSWORD:-conductor}
      CJSE_CONDUCTOR_ELASTICSEARCH_URL: ${CJSE_CONDUCTOR_ELASTICSEARCH_URL:-http://elasticsearch:9200}
      CJSE_CONDUCTOR_ELASTICSEARCH_VERSION: ${CJSE_CONDUCTOR_ELASTICSEARCH_VERSION:-6}
      CJSE_CONDUCTOR_DB_TYPE: ${CJSE_CONDUCTOR_DB_TYPE:-memory}
      CJSE_CONDUCTOR_INDEXING_ENABLED: ${CJSE_CONDUCTOR_INDEXING_ENABLED:-false}
      CJSE_CONDUCTOR_UI_USERNAME: ${CJSE_CONDUCTOR_UI_USERNAME:-bichard}
      CJSE_CONDUCTOR_UI_PASSWORD: ${CJSE_CONDUCTOR_UI_PASSWORD:-password}
      CJSE_CONDUCTOR_ENABLE_HTTP: "true"
      CJSE_CONDUCTOR_QUEUE_TYPE: "sqs"
      CJSE_CONDUCTOR_QUEUE_ENDPOINT: "http://localstack:4566"
      AWS_SECRET_ACCESS_KEY: FAKE
      AWS_ACCESS_KEY_ID: FAKE
      AWS_REGION: eu-west-2

    healthcheck:
      test: ["CMD", "curl", "--insecure", "--fail", "https://localhost:5000/health"]
      interval: "2s"
      timeout: "5s"
      retries: 60
    ports:
      - 5001:5000
      - 5002:4000

  elasticsearch:
    image: elasticsearch:6.8.15
    # image: elasticsearch:7.17.3
    platform: linux/amd64
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9300'
      interval: 5s
      timeout: 5s
      retries: 100
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  worker:
    build:
      context: ..
      dockerfile: conductor/Dockerfile
    environment:
      PHASE1_COMPARISON_TABLE_NAME: bichard-7-production-comparison-log
      PHASE2_COMPARISON_TABLE_NAME: bichard-7-production-phase2-comparison-log
      PHASE3_COMPARISON_TABLE_NAME: bichard-7-production-phase3-comparison-log
      COMPARISON_BUCKET: comparisons
      DYNAMO_REGION: eu-west-2
      DYNAMO_URL: http://localstack:4566
      S3_REGION: eu-west-2
      CONDUCTOR_URL: http://conductor:4000/api
      CONDUCTOR_USERNAME: ${CJSE_CONDUCTOR_UI_USERNAME:-bichard}
      CONDUCTOR_PASSWORD: ${CJSE_CONDUCTOR_UI_PASSWORD:-password}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_SECURITY_TOKEN: ${AWS_SECURITY_TOKEN}
      DYNAMO_AWS_ACCESS_KEY_ID: FAKE
      DYNAMO_AWS_SECRET_ACCESS_KEY: FAKE
      S3_AWS_ACCESS_KEY_ID: FAKE
      S3_AWS_SECRET_ACCESS_KEY: FAKE
      S3_ENDPOINT: http://localstack:4566

  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "4566:4566"
    volumes:
      - "${PWD}/environment/localstack/init:/etc/localstack/init"
    environment:
      SERVICES: "s3,sqs,dynamodb"
      AWS_DEFAULT_REGION: "eu-west-2"
    healthcheck:
      test: "timeout 2 bash -c \"curl -s localhost:4566/_localstack/init | grep -q '\\\"READY\\\": true'\""
      interval: 2s
      timeout: 2s
      retries: 100
