export enum PncOperation {
  COMMITTED_SENTENCING = "COMSEN",
  NORMAL_DISPOSAL = "DISARR",
  REMAND = "NEWREM",
  SENTENCE_DEFERRED = "SENDEF",
  DISPOSAL_UPDATED = "SUBVAR",
  PENALTY_HEARING = "PENHRG"
}
