name: MoJ Code Formatter

on:
  pull_request:

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ministryofjustice/github-actions/code-formatter@v18.2.2
        with:
          ignore-files: "**/tests/fixtures/e2e-comparison/*.json,**/help/**/*.md,docs/**/*.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
