name: Code Formatter

on:
  pull_request:

permissions:
  contents: write

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: ⛓️ SLSA Supply Chain Security
        uses: ministryofjustice/devsecops-actions/sca/slsa@7dc13c20e2bf541b8a77fa1320a04983b18846f6 # v1.6.0

      - uses: ./.github/actions/code-formatter
        with:
          ignore-files: "**/tests/fixtures/e2e-comparison/*.json,**/help/**/*.md,*.py,docs/architecture/workspace.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
