name: MoJ Code Formatter

on:
  pull_request:

permissions:
  contents: write

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
      - name: ⛓️ SLSA Supply Chain Security
        uses: ministryofjustice/devsecops-actions/sca/slsa@8c77d3a65a46d1d4b5416eafae5b84371ecd797d # v1.5.0

      - uses: ministryofjustice/github-actions/code-formatter@db1a54895bf5fb975c60af47e5a3aab96505ca3e #v18.6.0
        with:
          ignore-files: "**/tests/fixtures/e2e-comparison/*.json,**/help/**/*.md,*.py,docs/architecture/workspace.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
