name: Lint and build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version-file: .nvmrc

      - name: ⛓️ SLSA Supply Chain Security
        uses: ministryofjustice/devsecops-actions/sca/slsa@8c77d3a65a46d1d4b5416eafae5b84371ecd797d # v1.5.0
        with:
          security-patch-package-exclusion: '@moj-bichard7-developers/bichard7-next-data' # for release workflow

      - name: Install NPM packages
        run: npm ci --ignore-scripts

      - name: Run linting
        run: npm run lint:ci

      - name: Build Core Packages
        run: npm run build:core
