name: Lint and build

on:
  workflow_dispatch:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  test:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc

      - name: ⛓️ SLSA Supply Chain Security
        uses: ministryofjustice/devsecops-actions/sca/slsa@7dc13c20e2bf541b8a77fa1320a04983b18846f6 # v1.6.0
        with:
          security-patch-package-exclusion: '@moj-bichard7-developers/bichard7-next-data' # for release workflow

      - name: Install NPM packages
        run: npm ci --ignore-scripts

      - name: Run linting
        run: npm run lint:ci

      - name: Build Core Packages
        run: npm run build:core
