name: Test Common

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  changes:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read
    
    outputs:
      should_run: ${{ steps.paths-filter.outputs.github == 'true' || steps.paths-filter.outputs.env == 'true' || steps.paths-filter.outputs.common == 'true' }}

    steps: 
      - name: Checkout repository
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
        with: 
          fetch-depth: 0

      - name: Path Filtering
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: paths-filter
        with:
          filters: |
            github:
              - '.github/**'
            env:
              - 'environment/**'
            common:
              - 'packages/common/**'

  test_common:
    name: Test Common
    needs: changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        if: ${{ needs.changes.outputs.should_run == 'true' }}
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4

      - name: Setup node version
        if: ${{ needs.changes.outputs.should_run == 'true' }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version-file: .nvmrc

      - name: ⛓️ SLSA Supply Chain Security
        if: ${{ needs.changes.outputs.should_run == 'true' }}
        uses: ministryofjustice/devsecops-actions/sca/slsa@805c9da24fe7083e24b8435a626463b25951d278 # v1.4.0
      
      - name: Install dependencies
        if: ${{ needs.changes.outputs.should_run == 'true' }}
        run: npm ci --ignore-scripts

      - name: Run Unit Test Common
        if: ${{ needs.changes.outputs.should_run == 'true' }}
        run: npm run test -w packages/common

      - name: Skip Notification
        if: ${{ needs.changes.outputs.should_run != 'true' }}
        run: echo "No relevant paths modified. Skipping tests."
