name: Update npm dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  update_deps:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup node version
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: '.nvmrc'
        
      - name: Print node version  
        run: node -v

      - name: ⛓️ SLSA Supply Chain Security
        uses: ministryofjustice/devsecops-actions/sca/slsa@7dc13c20e2bf541b8a77fa1320a04983b18846f6 # v1.6.0
        with:
          security-patch-package-exclusion: '@moj-bichard7-developers/bichard7-next-data' # for release workflow

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Update dependencies
        run: npm run update-deps --workspaces

      - name: Report Status
        if: failure()
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d #v2.0.0
        with:
          webhook-type: incoming-webhook
          payload: |
            text: "GitHub action failed"  
            attachments:  
              - color: "#a30000" # Red  
                blocks:  
                  - type: "section"  
                    text:  
                      type: "mrkdwn"  
                      text: ":elmo-fire: *${{ github.workflow }}* failed in <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"  
                  - type: "context"  
                    elements:  
                      - type: "mrkdwn"  
                        text: "Linked to Repo <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

      - name: Create pull request
        id: cpr
        uses: ./.github/actions/create-pull-request
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "auto/update-npm-deps"
          commit_message: "Update npm dependencies"
          pr_title: "Update npm dependencies"
          update_type: "npm dependency updates"

      - name: Check PR information
        run: |
          echo "PR #${{ steps.cpr.outputs.pull-request-number}}"
          echo "${{ steps.cpr.outputs.pull-request-url }}"
